### ISSUE TITLE
IQTools DB Refresh Error - Erroneous BPs

### ISSUE THREAD

**Issue by thnesh** [palladium-group/IQTools#1]
![3 8 0 3 error 2](https://user-images.githubusercontent.com/31725448/30153611-e27f5eee-93bf-11e7-9d78-994d605819d0.jpg)
This is the error generated when refreshing the IQTools DB and its making tmp_ClinicalEnconters & tmp_OIs not have data

**Comment by chris-githu** [comment]
@thnesh Which IQCare DB are you seeing this error with?

**Comment by thnesh** [comment]
IQCare Ver 4.0.0 for Chogoria

https://www.dropbox.com/s/adtjkdoyvv8affu/IQCare-Deidentified-4.0.0%20Chogoria%20%28PCEA%29%20Hospital2017-09-06.7z?dl=0

**Comment by chris-githu** [comment]
@thnesh Looks like we have some erroneous BPs recorded. IQTools tries to convert these into `120/80` format and that is failing.

Going forward, I will change `tmp_ClinicalEncounters` to have a separate column for BPS and BPD. This will allow us to analyze for Hypertension, data entry errors and also avoid this error during load.

See below screenshot

![bp](https://user-images.githubusercontent.com/13725334/30155648-0902dc02-93c6-11e7-8036-ae2da10df084.PNG)

I'll be updating **beta** in a short while

Thanks.

**Comment by thnesh** [comment]
There might be need for a linelist to flag out abnormal vitals for update and DQA

**Comment by chris-githu** [comment]
@thnesh This should ideally be handled (validated) during data entry in IQCare
Please test whether IQCare v4 still allows such BPs. If it does, create an enhancement request in asana.

Thanks.
