### ISSUE TITLE
Return Old 731

### ISSUE THREAD

**Issue by vogoti** [palladium-group/IQTools#10]
The New MOH 731 doesn't have section 1 & 2.Could you please avail for us the old Version of MOH 731 to assist facilities in reporting since the new version has not been adopted by counties and DHIS is still using it

**Comment by chris-githu** [comment]
After discussions with all teams, we will be adding back the old 731 report to IQTools.

**Comment by thnesh** [comment]
Thanks @chris-githu for this update

**Comment by chris-githu** [comment]
Complete
