### ISSUE TITLE
SMS Appointment Queries

### ISSUE THREAD

**Issue by vogoti** [palladium-group/IQTools#11]
The Send SMS Tab under Messaging is not populating appointments category,its thus not possible to update SMS queries for facilities using SMS reminders
![sms screen](https://user-images.githubusercontent.com/31826771/31057376-4f47ce5c-a6ea-11e7-810c-17bedd396cd5.JPG)

**Comment by chris-githu** [comment]
@vogoti Noted.
Let's please try and catch such issues at testing phase next time.
Thanks.

**Comment by vogoti** [comment]
Thanks and noted

**Comment by chris-githu** [comment]
@vogoti Do we have a standard set of queries for `Appointments`?
Please reply to this thread `txt` attachments.

**Comment by thnesh** [comment]
@Chris @vogoti The standard set of queries that we were using during deployment are attached. I have not had the time to test it in IQCare 4.0.0
[SMS_Reminder_Queries.txt](https://github.com/palladium-group/IQTools/files/1374879/SMS_Reminder_Queries.txt)

**Comment by vogoti** [comment]
@thnesh @chris-githu Please also find attached Query for next appointment alert
[NextAppointment.txt](https://github.com/palladium-group/IQTools/files/1374953/NextAppointment.txt)

**Comment by vogoti** [comment]
@thnesh for the selection **'select ptn_pk from DTL_FBCUSTOMFIELD_Patient_Registration where SMSConsented=1'**,is the field SMSConsented for all DBs or in some it is ConsentedToSMS?

**Comment by chris-githu** [comment]
One other thing, the appointment reasons _('support group meeting', 'Treatment preparation')_, are they standard in all CHAP sites?

**Comment by thnesh** [comment]
Yes

**Comment by thnesh** [comment]
@chris-githu current splint has just the 'Next Appointment Alert' but other appointments reasons are missing. Also there need to be a next Appointment who have consented to SMS contact.

**Comment by thnesh** [comment]
???

**Comment by chris-githu** [comment]
Does this work in IQCare v4?


_Support Group Meeting_

`select distinct a.PatientPK, a.PatientName, a.PatientID, a.PhoneNumber as Phone,      
a.AgeCurrent, b.appdate as NextAppointmentDate, c.name as AppReason  from tmp_PatientMaster a     
inner join dtl_patientappointment b on a.patientpk= b.ptn_pk     
left join mst_decode c on b.appreason = c.id     
where b.appdate=CAST(@Appointment_Date as datetime)     
and a.PhoneNumber is not null  
and c.name = 'support group meeting' 
and a.patientpk in (select ptn_pk from DTL_FBCUSTOMFIELD_Patient_Registration where SMSConsented=1)`

**Comment by thnesh** [comment]
No, the support group meeting as a followup reason is not in the clinical encounter form.

**Comment by thnesh** [comment]
I Would suggest we retain the query so that eventually when its added since it will be needed, IQTools will not need an update.

**Comment by thnesh** [comment]
Also something that will be needed but was not in the previous reasons since it was not rolled out previously is the Differentiated care. Rpt_PatientAppointmentReason has the appointment reasons in the GreenCard clinical encounter.

**Comment by chris-githu** [comment]
@thnesh 
Please open this issue as a new request in chap-uzima

_Also something that will be needed but was not in the previous reasons since it was not rolled out previously is the Differentiated care. Rpt_PatientAppointmentReason has the appointment reasons in the GreenCard clinical encounter._

I will close this issue as we have resolved the original problem
