### ISSUE TITLE
MOH 731 Current On ART

### ISSUE THREAD

**Issue by mkaburu** [palladium-group/IQTools#12]
Looking at the query that generates this indicator; should it check the AgeARTStart or AgeLastVisit?

**Comment by chris-githu** [comment]
`Select a.Gender
,    dbo.fn_GetAgeGroup(a.AgeARTStart, 'MOH731') AgeGroup
,    Count(Distinct a.PatientPK) Total  From tmp_ARTPatients a  
Where a.RegistrationDate <= Cast(@todate As datetime)  
AND a.StartARTDate <= Cast(@todate As datetime) 
AND dbo.fn_ActiveCCC(Cast(@todate As datetime), a.PatientPK) = 1
Group By a.Gender, dbo.fn_GetAgeGroup(a.AgeARTStart, 'MOH731')`

Good catch @mkaburu It should use `AgeLastVisit`. I will make the update.

**Comment by thnesh** [comment]
This has been Updated

**Comment by chris-githu** [comment]
Thanks @thnesh
