### ISSUE TITLE
MOH 731 TB

### ISSUE THREAD

**Issue by mkaburu** [palladium-group/IQTools#17]
3.10 HIV in TB Clinic
Can we edit the query to pick the ART Start Date from the TB profile for patients who may be accessing CCC services from other facilities but TB medication in our facility?
This will help report accurately on the ART status for TB cases registered in the month

**Comment by chris-githu** [comment]
@mkaburu 
We can pick the ART start date from both sources. Just in case we have documentation gaps in the TB Module.

**Comment by chris-githu** [comment]
Hi @mkaburu 
Please confirm that this issue is resolved in 3.8.9

**Comment by mkaburu** [comment]
Not quite. You might have patients who are HIV positive but pick their drugs from another facility. e.g. the screenshot attached; this patient is not enrolled in Tumutumu but is HIV positive and is on ART. In the MOH 731 line lists HIV in TB clinic tab  this patient is counted as not on ART but from the data in the TB profile they are already on ART
![tbart](https://user-images.githubusercontent.com/31726479/33553938-c58028aa-d90b-11e7-9dba-229129400b7f.PNG)

**Comment by chris-githu** [comment]
@mkaburu This has already been considered in the query.
Please check whether the _tmp_TBPatients_ table shows that this client has a _StartARTDate_

**Comment by mkaburu** [comment]
Yes it has . Sorted now
