### ISSUE TITLE
Nutrition and HIV

### ISSUE THREAD

**Issue by thnesh** [palladium-group/IQTools#2]
Nutrition Assessment and Malnourished not populating in the 731 report. This data is captured in the clinical encounter

**Comment by chris-githu** [comment]
@thnesh Yes, we have not designed queries for these yet. Anything in gray on the 731 report is still pending. Since this data becomes available in IQCare 4.0, we have scheduled for the next IQTools release.

**Comment by chris-githu** [comment]
3.9   Nutrition and HIV |  
-- | --
Nutrition Assessment <15 | HV03-67
Nutrition Assessment 15+ | HV03-68
Nutrition Assessment Total | HV03-69
Malnourished <15 | HV03-70
Malnourished 15+ | HV03-71
Malnourished Total | HV03-72
FBP Provided <15 | HV03-73
FBP Provided 15+ | HV03-74
FBP Provided Total | HV03-75

**Comment by chris-githu** [comment]
@thnesh 
Please confirm that this is resolved in 3.8.9
Please note we are only reporting Assessment and Malnutrition.
FBP is not explicit as discussed last week.

**Comment by thnesh** [comment]
This is resolved in the latest sprint
