### ISSUE TITLE
MoH 731 - Key Populations

### ISSUE THREAD

**Issue by chris-githu** [palladium-group/IQTools#7]
Using `IQCare v4` Clinical Encounter

1. Enrolled   in Care Key Pop - HV03-012
2. Start   ART Key Pop - HV03-027
3. On ART   Key Pop - HV03-039

**Comment by thnesh** [comment]
This indicator is picking the Discondant couples who were previous picked in the At Risk Population in the blue card but according to the MER 2.0 indicator reference guide, this is not a KeyPop. I was testing using Mutomo DB and all the those appearing are discordant couples.
[MER 2.0 Indicator Reference Guide October 2017pdf.pdf](https://github.com/palladium-group/IQTools/files/1496445/MER.2.0.Indicator.Reference.Guide.October.2017pdf.pdf)

**Comment by chris-githu** [comment]
Noted.
@mkaburu FYI

**Comment by chris-githu** [comment]
@thnesh Please confirm that this is resolved in 3.8.9

**Comment by thnesh** [comment]
@chris-githu Resolved
